# docker-compose.yml  
version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flaskdb
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 5s

  web:
    build: ./backend
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: flaskdb
    ports: ["5000:5000"]
    depends_on:
      db:
        condition: service_healthy
