version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
  web:
    build: ./backend
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: flaskdb
    ports:
      - "5000:5000"
    depends_on:
      - db